############################
## loki chart section     ##
############################
# Enables minio for Loki
loki:
  sidecar:
    enableUniqueFilenames: true
    rules:
      folder: "/var/loki/rules/fake"
  loki:
    # disables auth
    auth_enabled: false
    # ruler config for alerts
    rulerConfig:
      storage:
        type: local
        local:
          directory: /var/loki/rules
      rule_path: /var/loki/rules
      alertmanager_url: http://alertmanager-operated:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true
      enable_alertmanager_v2: true
  # enables minio for logs storage
  minio:
    enabled: true
    rootUser: admin
    rootPassword: admin123

############################
## promtail chart section ##
############################
promtail:
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push