apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  labels:
    app.kubernetes.io/name: loki-grafana-datasource
    app.kubernetes.io/instance: loki-grafana-datasource-1.0.0
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: datasource
    app.kubernetes.io/part-of: loki-alerts
    app.kubernetes.io/managed-by: helm
    grafana_datasource: '1'
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway
        access: proxy